./raytracer1b ./example1.txt
./raytracer1b ./example2.txt
./raytracer1b ./example3.txt
./raytracer1b ./example4.txt
./raytracer1b ./example5.txt
./raytracer1b ./parallel.txt
./raytracer1b ./ambientcoefficient.txt
./raytracer1b ./diffusecoefficient.txt
./raytracer1b ./specularcoefficient.txt
./raytracer1b ./directionallight.txt
