./raytracer1b ./tests/example1.txt
./raytracer1b ./tests/example2.txt
./raytracer1b ./tests/example3.txt
./raytracer1b ./tests/example4.txt
./raytracer1b ./tests/example5.txt
./raytracer1b ./tests/parallel.txt
./raytracer1b ./tests/ambientcoefficient.txt
./raytracer1b ./tests/diffusecoefficient.txt
./raytracer1b ./tests/specularcoefficient.txt
./raytracer1b ./tests/directionallight.txt
